name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 9898
          script: |
            cd /home/safefood/public_html/node
            git pull origin main
            rsync -av --exclude='.git' --exclude='.github' /home/safefood/public_html/node/ /home/safefood/public_html/
            find /home/safefood/public_html -type f -exec chmod 644 {} \;
            find /home/safefood/public_html -type d -exec chmod 755 {} \;
